# Copyright (c) 2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v2 or later

version: 2
updates:

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "Actions"
    directory: "/"
    labels:
      - "enhancement"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    commit-message:
      include: "scope"
      prefix: "requirements"
    directory: "/"
    labels:
      - "enhancement"
    schedule:
      interval: "daily"
